### ISSUE TITLE
build/ folder shall be removed.

### ISSUE THREAD

**Issue by vinjn** [egoist-sx/ORB_SLAM_iOS#1]
You can use this file as `.gitignore` for iOS projects.

https://github.com/github/gitignore/blob/master/Global/Xcode.gitignore

**Comment by egoist-sx** [comment]
Thanks! I will clean up the repo a bit today.

**Comment by egoist-sx** [comment]
@vinjn Checkout new push, it includes a fix on corrupted dependency folder.
