### ISSUE TITLE
Is there an orb_slam version2 port?

### ISSUE THREAD

**Issue by skylook** [egoist-sx/ORB_SLAM_iOS#2]
Thank you for the great job! 
It seems v2 of orb_slam get a better performance. And also it removes the ros dependancy.
Can you port a v2 version of orb_slam to iOS? Thanks

**Comment by egoist-sx** [comment]
I have just checked orb_slam v2, it seems performance boost is not significant and the biggest problems are not solved(pure rotation and slow mapping thread). This iOS version has already removed ros dependancy. It will not worth the effort to spend time on v2 other than you want to use stereo/rgbd camera.
