### ISSUE TITLE
trouble exporting keyframe/map data

### ISSUE THREAD

**Issue by stanchiang** [egoist-sx/ORB_SLAM_iOS#3]
I tried using the save functions in DBoW2 to save the mapping data collected while the app was running, but I ran into issues with all 3 save functions. 

The end goal is to save my mapping data and the 3d object orientation and position such that I can load it at a future time and eliminate the need to remap the same space every time the app loads. 

This should be possible to implement right?

the std::of stream based methods in TemplatedVocabulary didn't work and i also tried something like the code below to write to an existing file below but it would never open it even though the obj-c code could open it fine.

``````
     path = [[[NSBundle mainBundle]pathForResource:@"savedvoc" ofType:@"txt"] cStringUsingEncoding:[NSString defaultCStringEncoding]];
        std::of stream file

        file.open(path, std::ios::out | std::ios::app );
        if (file.is_open()) {
            file << "some text\n";
            file.close();

            std::if stream rf

            rf.open(path, std::ios::in );

            char str[255];
            while(rf) {
                rf.getline(str, 255);

                if(rf) printf("%s", str);

            }

            rf.close();

        }else {

```;


additionally i tried using cv::file storage which could find the file but it never actually wrote anything to file.

``````

cv::FileStorage testfile(path, cv::FileStorage::WRITE);
_Tracker->mpORBVocabulary->save(testfile); //i made the mpORBVocabulary var public as a quick way to access the variable

``` ;

i even called Size() on the mpORBVocabulary var to make sure there was content to write in the first place. 
```

**Comment by egoist-sx** [comment]
@stanchiang I think there are two different problems. I haven't check DBoW2 saving function, but I believe it only contains vocabulary info, and what you want is the real map generated during slam. You could dump all points along with their vocabulary encoding into a txt file. The second issue is how could you write file in iOS, mainbundle is where you put file on iOS, for example "[[[NSBundle mainBundle]pathForResource:@"savedvoc" ofType:@"txt"]" specified "savedvoc.txt" in Xcode project, which does not exit (because you never added it in your xcode project). If you want to write file, I suggest you look at how you get Document directory path with Objective-C api, and use C++ to write it.

**Comment by stanchiang** [comment]
Ah thanks. I got the file saving component figured out. 

To confirm, all the real map data I need is contained in the mpMap variable with the arrays for keyframe and mappoint?

also am I understanding correctly that if i reload my saved map data, that it is the Tracking::Relocalisation() function that will loop through my map data to figure out where i am in the map?

**Comment by egoist-sx** [comment]
@stanchiang I am afraid map points can only used for tracking, if you want relocalization, you probably want to save vocabulary in each KF.

**Comment by stanchiang** [comment]
Could you elaborate on what you mean by the vocabulary in each KF? 

Also as of right now I'm using this sample code as a starting point for exporting https://github.com/mojovski/ORB_SLAM/blob/export_nvm_2/src/main.cc

which is from this thread
https://github.com/raulmur/ORB_SLAM/issues/73#issuecomment-246463446

And if you have any interest in adding this functionality, your help would be much appreciated.  @mojovski (from that thread) and i will be trying to put something together.

**Comment by egoist-sx** [comment]
@stanchiang In KeyFrame.hpp declared "ORBVocabulary\* mpORBvocabulary", and please check cpp for detail. I am currently really busy, and afraid could not spare any time working on SLAM related projection.

**Comment by ghost** [comment]
@stanchiang I think the relocalization topic deserves its own github project (can also be a fork of orb slam). Would you like to create a fork? I would love to join then and discuss more stuff without bothering the author here. :)

PS: For relocalization, basically this library is used in ORB slam: https://github.com/dorian3d/DBoW2 

> library for indexing and converting images into a bag-of-word representation
