### ISSUE TITLE
GPL Violation

### ISSUE THREAD

**Issue by raulmur** [egoist-sx/ORB_SLAM_iOS#5]
ORB-SLAM is licensed under GPLv3, so in order to redistribute it you have to do it under the terms of that license. You cannot remove the original copyright and GPL terms and you have to explicitly state that this is a modified version. Moreover your whole project has to be licensed under GPLv3.
See https://github.com/raulmur/ORB_SLAM/blob/master/License-gpl.txt

Please do the appropriate modifications to your repository.

**Comment by egoist-sx** [comment]
@raulmur Hey there, sorry for late reply. I have pushed an update with original licence information.
